# Generated by Django 5.2.10 on 2026-01-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('nome_de_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('saram', models.CharField(max_length=20, unique=True, verbose_name='SARAM/Matrícula')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato/Email')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título da Função')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={
                'verbose_name': 'Tipo de Função',
                'verbose_name_plural': 'Tipos de Função',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PostoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição Completa')),
                ('senioridade', models.IntegerField(default=0, verbose_name='Ordem de Antiguidade')),
            ],
            options={
                'verbose_name': 'Posto/Graduação',
                'verbose_name_plural': 'Postos e Graduações',
                'ordering': ['senioridade'],
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FISCALIZACAO', 'Equipe de Fiscalização'), ('RECEBIMENTO', 'Comissão de Recebimento'), ('SINDICANCIA', 'Sindicância')], max_length=20, verbose_name='Tipo da Comissão')),
                ('ativa', models.BooleanField(default=True, verbose_name='Comissão Ativa?')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.empresa', verbose_name='Empresa Contratada'),
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início (Designação)')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término conforme portaria', null=True, verbose_name='Término Previsto')),
                ('portaria_numero', models.CharField(max_length=50, verbose_name='Nº Portaria')),
                ('portaria_data', models.DateField(verbose_name='Data da Portaria')),
                ('boletim_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Boletim')),
                ('boletim_data', models.DateField(blank=True, null=True, verbose_name='Data do Boletim')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Obs')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.agente', verbose_name='Militar')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='contratos.comissao')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Histórico de Integrantes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='agente',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.postograduacao', verbose_name='Posto/Graduação'),
        ),
    ]
