# Generated by Django 5.2.10 on 2026-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='observacao',
        ),
        migrations.AddField(
            model_name='agente',
            name='data_ultimo_curso',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Curso de Gestão'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.CharField(choices=[('FISCALIZACAO', 'Fiscalização (Gestor/Fiscal)'), ('RECEBIMENTO', 'Recebimento (Pres/Membros)')], default='FISCALIZACAO', max_length=20),
        ),
    ]
