# Generated by Django 5.2.10 on 2026-01-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_comissao_observacao_agente_data_ultimo_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='data_desligamento',
            field=models.DateField(blank=True, help_text='Preencher apenas em caso de saída antecipada ou substituição.', null=True, verbose_name='Data Efetiva de Saída'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='doc_desligamento',
            field=models.CharField(blank=True, help_text='Portaria ou Boletim que publicou a dispensa.', max_length=50, null=True, verbose_name='Doc. de Desligamento'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='motivo_desligamento',
            field=models.CharField(blank=True, help_text='Ex: Dispensa a pedido, Transferência, Término de Vigência.', max_length=100, null=True, verbose_name='Motivo da Saída'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data de término conforme portaria original', null=True, verbose_name='Término Previsto'),
        ),
    ]
