# Generated by Django 5.2.10 on 2026-01-31 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_integrante_data_desligamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='posto_graduacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratos.postograduacao', verbose_name='Posto na Época'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.postograduacao', verbose_name='Posto Atual'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Efetiva de Saída'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Término Previsto'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='doc_desligamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc. de Desligamento'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='motivo_desligamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Saída'),
        ),
    ]
