# Generated by Django 5.2.10 on 2026-02-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_integrante_posto_graduacao_alter_agente_posto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Comissão'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Comissão'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='portaria_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Portaria'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='portaria_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Portaria da Comissão'),
        ),
    ]
