# Generated by Django 5.2.10 on 2026-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_comissao_data_fim_comissao_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='boletim_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Boletim'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='boletim_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Boletim'),
        ),
    ]
