# Generated by Django 5.2.10 on 2026-02-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_comissao_boletim_data_comissao_boletim_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contato',
        ),
    ]
