# Generated by Django 5.2.10 on 2026-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_remove_empresa_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='DESPESA', max_length=10, verbose_name='Tipo'),
        ),
    ]
