# Generated by Django 5.2.10 on 2026-02-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contrato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.CharField(choices=[('FISCALIZACAO', 'Fiscalização'), ('RECEBIMENTO', 'Recebimento')], default='FISCALIZACAO', max_length=20),
        ),
    ]
