# Generated by Django 5.2.10 on 2026-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_alter_comissao_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Tipo de Função', 'verbose_name_plural': 'Tipos de Função'},
        ),
        migrations.AddField(
            model_name='funcao',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Hierarquia'),
        ),
    ]
