# Generated by Django 5.2.10 on 2026-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_alter_funcao_options_funcao_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['ordem'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Histórico de Integrantes'},
        ),
        migrations.AddField(
            model_name='integrante',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
