# Generated by Django 5.2.10 on 2026-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_alter_integrante_options_integrante_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo Administrativo de Gestão (PAG)'),
        ),
    ]
