# Generated by Django 5.2.10 on 2026-02-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_contrato_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
