# Generated by Django 5.2.10 on 2026-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_agente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
