# Generated by Django 5.2.10 on 2026-05-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_comissao_ativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['tipo'], 'verbose_name': 'Comissão', 'verbose_name_plural': 'Comissões'},
        ),
    ]
