# Generated by Django 5.2.10 on 2026-05-21 18:47

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_comissao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('arquivo', models.FileField(upload_to=contratos.models.upload_prestacao_path, verbose_name='Arquivo PDF')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.agente', verbose_name='Fiscal')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Prestação de Contas',
                'verbose_name_plural': 'Prestações de Contas',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('contrato', 'ano_referencia', 'mes_referencia')},
            },
        ),
    ]
