# Generated by Django 5.2.10 on 2026-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_prestacaocontas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='status',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('correcao', 'Aguardando Correção'), ('ok', 'Conformidade (OK!)')], default='entregue', max_length=15, verbose_name='Status'),
        ),
    ]
