# Generated by Django 5.2.10 on 2026-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_prestacaocontas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='compor_apresentacao',
            field=models.BooleanField(default=False, help_text='Marque se este slide fará parte da apresentação consolidada', verbose_name='Compor Apresentação'),
        ),
    ]
