# Generated by Django 5.2.10 on 2026-05-28 13:57

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_prestacaocontas_compor_apresentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaocontas',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=contratos.models.upload_prestacao_path, verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='prestacaocontas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('correcao', 'Aguardando Correção'), ('ok', 'Conformidade (OK!)')], default='entregue', max_length=15, verbose_name='Status'),
        ),
    ]
