# Generated by Django 5.2.10 on 2026-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_alter_prestacaocontas_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='ordem_manual',
            field=models.FloatField(default=0.0, verbose_name='Ordem Manual'),
        ),
    ]
