# Generated by Django 5.2.10 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_agente_ordem_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
