# Generated by Django 5.2.10 on 2026-05-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_empresa_nome_fantasia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prestacaocontas',
            unique_together=set(),
        ),
    ]
