# Generated by Django 5.2.10 on 2026-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_alter_prestacaocontas_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega dos Slides')),
                ('data_apresentacao', models.DateField(blank=True, null=True, verbose_name='Data Prevista da Apresentação')),
            ],
            options={
                'verbose_name': 'Calendário de Prestação',
                'verbose_name_plural': 'Calendários de Prestação',
                'ordering': ['ano', 'mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
