# Generated by Django 5.2.10 on 2026-05-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_calendarioprestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CargoRegimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('boletim_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do Boletim')),
                ('boletim_data', models.DateField(blank=True, null=True, verbose_name='Data do Boletim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.agente', verbose_name='Gestor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='contratos.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Cargo Regimental',
                'verbose_name_plural': 'Cargos Regimentais',
                'ordering': ['setor__ordem', 'setor__nome', 'cargo'],
            },
        ),
    ]
