# Generated by Django 5.2.10 on 2026-05-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_setor_cargoregimental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoCorrecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição das Inconsistências')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='contratos.prestacaocontas')),
            ],
            options={
                'verbose_name': 'Apontamento de Correção',
                'verbose_name_plural': 'Apontamentos de Correção',
                'ordering': ['-data_registro'],
            },
        ),
    ]
