# Generated by Django 5.2.10 on 2026-05-30 01:34

import contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_apontamentocorrecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContasSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=contratos.models.upload_prestacao_setor_path, verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('correcao', 'Aguardando Correção'), ('ok', 'Conformidade (OK!)')], default='entregue', max_length=15, verbose_name='Status')),
                ('compor_apresentacao', models.BooleanField(default=False, help_text='Marque se este slide fará parte da apresentação consolidada', verbose_name='Compor Apresentação')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.agente', verbose_name='Gestor do Setor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_setor', to='contratos.setor')),
            ],
            options={
                'verbose_name': 'Prestação de Contas (Setor)',
                'verbose_name_plural': 'Prestações de Contas (Setores)',
                'ordering': ['-ano_referencia', '-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ApontamentoCorrecaoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição das Inconsistências')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='contratos.prestacaocontassetor')),
            ],
            options={
                'verbose_name': 'Apontamento de Correção (Setor)',
                'verbose_name_plural': 'Apontamentos de Correção (Setores)',
                'ordering': ['-data_registro'],
            },
        ),
    ]
