# Generated by Django 5.2.10 on 2026-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_prestacaocontassetor_apontamentocorrecaosetor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarioprestacao',
            name='data_apresentacao',
        ),
        migrations.AddField(
            model_name='calendarioprestacao',
            name='data_apresentacao_fiscais',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Apresentação - Fiscais'),
        ),
        migrations.AddField(
            model_name='calendarioprestacao',
            name='data_apresentacao_gestores',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Apresentação - Gestores'),
        ),
    ]
