# Generated by Django 5.2.10 on 2026-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_remove_calendarioprestacao_data_apresentacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_diretorio', models.CharField(default='/var/backups/siscont', help_text='Caminho absoluto onde os backups serão salvos.', max_length=255, verbose_name='Diretório de Backup')),
                ('backup_periodicidade', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='diario', max_length=15, verbose_name='Periodicidade do Backup')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
