# Generated by Django 5.2.10 on 2026-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_configuracaosistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='backup_diretorio',
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='backup_periodicidade',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='diario', help_text='Frequência com que o backup automatizado será executado.', max_length=20, verbose_name='Periodicidade do Backup'),
        ),
    ]
