# Generated by Django 5.2.10 on 2026-06-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_remove_configuracaosistema_backup_diretorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Comissão de Contrato'), ('OUTRAS', 'Outras Comissões')], default='CONTRATO', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='descricao_objeto',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Objeto'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.CharField(choices=[('FISCALIZACAO', 'Fiscalização'), ('RECEBIMENTO', 'Recebimento de Contrato'), ('RECEBIMENTO_GERAL', 'Recebimento (geral)'), ('PLANEJAMENTO', 'Planejamento'), ('AVALIACAO', 'Avaliação'), ('EXAME', 'Exame'), ('LICITACAO', 'Licitação/Contratação'), ('DIVERSAS', 'Diversas')], default='FISCALIZACAO', max_length=20),
        ),
    ]
