# Generated by Django 5.2.10 on 2026-06-15 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_comissao_categoria_comissao_descricao_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='codigo_siloms',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'O código SILOMS deve conter exatamente 10 dígitos numéricos.')], verbose_name='Código SILOMS'),
        ),
    ]
