# Generated by Django 5.2.10 on 2026-06-23 12:07

import contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0031_comissao_codigo_siloms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apresentacao', models.CharField(choices=[('fiscais', 'Fiscais'), ('gestores', 'Gestores')], max_length=15, verbose_name='Tipo de Apresentação')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('nome_slide', models.CharField(max_length=100, verbose_name='Nome do Slide')),
                ('arquivo', models.FileField(upload_to=contratos.models.upload_slide_avulso_path, verbose_name='Arquivo PDF')),
                ('indice_posicao', models.FloatField(default=999.0, help_text='Define a ordem do slide na apresentação (menor valor aparece antes).', verbose_name='Posição na Apresentação')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Slide Avulso',
                'verbose_name_plural': 'Slides Avulsos',
                'ordering': ['indice_posicao', 'data_registro'],
            },
        ),
    ]
