# Generated by Django 5.2.10 on 2026-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_slideapresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='ordem_apresentacao',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Ordem na Apresentação'),
        ),
        migrations.AddField(
            model_name='prestacaocontassetor',
            name='ordem_apresentacao',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Ordem na Apresentação'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apresentacao', models.CharField(choices=[('fiscais', 'Fiscais'), ('gestores', 'Gestores')], max_length=15, verbose_name='Tipo de Apresentação')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('modo_livre', models.BooleanField(default=False, help_text='Se ativado, permite ordenar livremente a apresentação ignorando restrições de posto/graduação.', verbose_name='Modo Livre de Apresentação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Apresentação',
                'verbose_name_plural': 'Configurações da Apresentação',
                'unique_together': {('tipo_apresentacao', 'ano_referencia', 'mes_referencia')},
            },
        ),
    ]
