# Generated by Django 5.2.10 on 2026-07-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_slideapresentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioprestacao',
            name='data_entrega_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega do Livro do Fiscal'),
        ),
        migrations.CreateModel(
            name='ControleExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('correcao', 'Aguardando Correção'), ('ok', 'Conformidade (OK!)')], default='entregue', max_length=15, verbose_name='Status')),
                ('confirmacao_siloms_assinatura', models.BooleanField(default=False, verbose_name='Conferido com SILOMS (Assinatura)')),
                ('confirmacao_siloms_vigencia', models.BooleanField(default=False, verbose_name='Conferido com SILOMS/Aditivo (Vigência)')),
                ('confirmacao_siloms_execucao', models.BooleanField(default=False, verbose_name='Conferido com Cronograma/OS (Execução)')),
                ('possibilidade_aditivo', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=5, verbose_name='Possibilidade de aditivar contrato?')),
                ('tratativas_120_dias', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=5, verbose_name='Iniciadas tratativas 120 dias antes?')),
                ('coordenacao_doc_scon', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=5, verbose_name='Coordenada informação com DOC/SCON?')),
                ('notas_empenho', models.TextField(blank=True, verbose_name='Notas de Empenho (NEs Vigentes)')),
                ('obs_sem_empenho', models.TextField(blank=True, verbose_name='Obs. caso não haja empenho')),
                ('cronograma_fisico_financeiro', models.CharField(choices=[('conforme', 'Conforme o previsto'), ('atrasado', 'Atrasado')], default='conforme', max_length=10, verbose_name='Cumprimento do Cronograma Físico-Financeiro')),
                ('detalhamento_cronograma', models.TextField(blank=True, verbose_name='Status do Cronograma de Execução')),
                ('alteracao_cronograma', models.BooleanField(default=False, verbose_name='Houve alteração em relação ao mês anterior?')),
                ('alteracao_cronograma_desc', models.TextField(blank=True, verbose_name='Ações do fiscal (Alteração Cronograma)')),
                ('atraso_entrega', models.BooleanField(default=False, verbose_name='Atraso na entrega dos produtos/serviços?')),
                ('atraso_entrega_desc', models.TextField(blank=True, verbose_name='Ações do fiscal (Atraso Entrega)')),
                ('impossibilidade_recebimento', models.BooleanField(default=False, verbose_name='Impossibilidade de recebimento?')),
                ('impossibilidade_recebimento_desc', models.TextField(blank=True, verbose_name='Ações do fiscal (Impossibilidade)')),
                ('diligencia_visita', models.BooleanField(default=False, verbose_name='Realização de diligência ou visita técnica?')),
                ('diligencia_visita_desc', models.TextField(blank=True, verbose_name='Resultados obtidos e ações (Diligência)')),
                ('imr_aplicado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, verbose_name='Aplicado IMR?')),
                ('glosa_realizada', models.BooleanField(default=False, verbose_name='Realizada glosa no período?')),
                ('glosa_desc', models.TextField(blank=True, verbose_name='Detalhamento de glosa e valores')),
                ('relatorio_ocorrencias', models.TextField(blank=True, verbose_name='Relatório de Ocorrências e Tratativas')),
                ('ocorrencias_ativas_empresa', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, verbose_name='Ocorrências ativas por atraso/descumprimento reincidente?')),
                ('necessidade_paai', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, verbose_name='Necessária solicitação de abertura de PAAI neste mês?')),
                ('paai_justificativa', models.TextField(blank=True, verbose_name='Detalhamento de infrações / Justificativa PAAI')),
                ('houve_substituicao', models.BooleanField(default=False, verbose_name='Houve substituição do fiscal/membro no período?')),
                ('substituicao_entrega_formal', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=5, verbose_name='Entrega formal dos registros realizada pelo substituto?')),
                ('substituicao_obs', models.TextField(blank=True, verbose_name='Observações sobre a substituição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.agente', verbose_name='Fiscal')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_execucao', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Controle de Execução Contratual',
                'verbose_name_plural': 'Controles de Execução Contratual',
                'ordering': ['-ano_referencia', '-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ApontamentoCorrecaoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição das Inconsistências')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='contratos.controleexecucao')),
            ],
            options={
                'verbose_name': 'Apontamento de Correção (Execução)',
                'verbose_name_plural': 'Apontamentos de Correção (Execução)',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaContratual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Ocorrência')),
                ('tipo', models.CharField(default='outro', max_length=30, verbose_name='Tipo de Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('acao_fiscal', models.TextField(blank=True, verbose_name='Ação do Fiscal / Providência')),
                ('prazo', models.CharField(blank=True, max_length=50, verbose_name='Prazo para Resolução')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='contratos.controleexecucao')),
            ],
            options={
                'verbose_name': 'Ocorrência Contratual',
                'verbose_name_plural': 'Ocorrências Contratuais',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50, verbose_name='Nº da Nota Fiscal / Fatura')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor (R$)')),
                ('numero_ob', models.CharField(blank=True, max_length=50, verbose_name='Nº da Ordem Bancária (OB)')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='contratos.controleexecucao')),
            ],
            options={
                'verbose_name': 'Registro de Fatura',
                'verbose_name_plural': 'Registros de Faturas',
            },
        ),
    ]
