# Generated by Django 5.2.10 on 2026-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0033_calendarioprestacao_data_entrega_execucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleexecucao',
            name='garantia_providencias',
            field=models.TextField(blank=True, verbose_name='Providências adotadas (Garantia Vencida)'),
        ),
        migrations.AddField(
            model_name='controleexecucao',
            name='garantia_vigente',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não (Vencida)'), ('na', 'Não se aplica / Sem garantia')], default='na', max_length=10, verbose_name='Garantia contratual dentro da vigência?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='notas_empenho',
            field=models.TextField(blank=True, verbose_name='Notas de Empenho (com saldo)'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='possibilidade_aditivo',
            field=models.CharField(choices=[('sim', 'Sim'), ('na', 'Não há mais possibilidade/Não se aplica'), ('nao', 'Não há mais possibilidade/Não se aplica')], default='na', max_length=10, verbose_name='Contrato admite termo aditivo?'),
        ),
    ]
