# Generated by Django 5.2.10 on 2026-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0034_controleexecucao_garantia_providencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleexecucao',
            name='data_execucao_fisico_financeira',
            field=models.DateField(blank=True, null=True, verbose_name='Data término da execução físico-financeira'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='confirmacao_siloms_execucao',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=10, verbose_name='Conferido com Cronograma/OS (Execução)'),
        ),
    ]
