# Generated by Django 5.2.10 on 2026-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0035_controleexecucao_data_execucao_fisico_financeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleexecucao',
            name='alteracao_cronograma',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Houve alteração em relação ao mês anterior?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='atraso_entrega',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Atraso na entrega dos produtos/serviços?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='diligencia_visita',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Realização de diligência ou visita técnica?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='glosa_realizada',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Realizada glosa no período?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='impossibilidade_recebimento',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Impossibilidade de recebimento?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='imr_aplicado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='nao', max_length=5, verbose_name='Aplicado IMR?'),
        ),
        migrations.AlterField(
            model_name='controleexecucao',
            name='tratativas_120_dias',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('na', 'Não se aplica')], default='na', max_length=5, verbose_name='Iniciadas as tratativas para aditivação'),
        ),
    ]
