# Generated by Django 5.2.10 on 2026-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0036_alter_controleexecucao_alteracao_cronograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleexecucao',
            name='doc_sancao_siloms',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=5, null=True, verbose_name='Documentação comprobatória inserida no SILOMS?'),
        ),
        migrations.AddField(
            model_name='controleexecucao',
            name='empresa_sancionada',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=5, null=True, verbose_name='Empresa sancionada com impedimento de licitar e contratar e/ou declaração de inidoneidade para licitar ou contratar?'),
        ),
        migrations.AddField(
            model_name='controleexecucao',
            name='sancao_observacao',
            field=models.TextField(blank=True, verbose_name='Observações / Detalhamento da Sanção'),
        ),
    ]
