# Generated by Django 5.2.10 on 2026-08-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0037_controleexecucao_doc_sancao_siloms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoObservacaoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observação / Resposta do Fiscal')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.agente')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_observacoes', to='contratos.controleexecucao')),
            ],
            options={
                'verbose_name': 'Histórico de Observação (Execução)',
                'verbose_name_plural': 'Históricos de Observação (Execução)',
                'ordering': ['data_envio'],
            },
        ),
    ]
